/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantalla;

/**
 *
 * @author Jhon SM
 */
public class PantallaMesas extends javax.swing.JPanel {

    /**
     * Creates new form PantallaMesas
     */
    public PantallaMesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEquipos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBusqueda = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        cbestado = new javax.swing.JComboBox<>();
        btn_exporExcel = new javax.swing.JButton();
        txtnomequipo = new javax.swing.JTextField();
        jLabelfondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(128, 64, 0));
        jTextField2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 48)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("    Mesas disponibles");
        jTextField2.setAutoscrolls(false);
        jTextField2.setBorder(null);
        jTextField2.setFocusable(false);
        jTextField2.setRequestFocusEnabled(false);
        jTextField2.setVerifyInputWhenFocusTarget(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1080, 80));

        jTableEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID MESAS", "NOMBRE", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEquipos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 790, 490));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel2.setText("BUSCAR :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        txtBusqueda.setColumns(20);
        txtBusqueda.setRows(1);
        txtBusqueda.setToolTipText("");
        txtBusqueda.setAutoscrolls(false);
        jScrollPane3.setViewportView(txtBusqueda);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 380, 30));

        btnActualizar.setBackground(new java.awt.Color(102, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, 110, 40));

        add(cbestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 160, -1));

        btn_exporExcel.setBackground(new java.awt.Color(6, 99, 44));
        btn_exporExcel.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        btn_exporExcel.setForeground(new java.awt.Color(255, 255, 255));
        btn_exporExcel.setText("EXPORTAR A EXCEL");
        btn_exporExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exporExcelActionPerformed(evt);
            }
        });
        add(btn_exporExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, -1, 40));
        add(txtnomequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 160, -1));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btn_exporExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exporExcelActionPerformed

    }//GEN-LAST:event_btn_exporExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btn_exporExcel;
    private javax.swing.JComboBox<String> cbestado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableEquipos;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea txtBusqueda;
    private javax.swing.JTextField txtnomequipo;
    // End of variables declaration//GEN-END:variables
}
