/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantalla;

/**
 *
 * @author Jhon SM
 */
public class PantallaRegistroCliente extends javax.swing.JFrame {

    /**
     * Creates new form PantallaRegistroCliente
     */
    public PantallaRegistroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ApellidoPaterno = new javax.swing.JLabel();
        CorreoElectronico = new javax.swing.JLabel();
        NumeroDNI = new javax.swing.JLabel();
        nombres = new javax.swing.JLabel();
        BotonSubirImagen = new javax.swing.JButton();
        jTextFieldApellidoPCliente = new javax.swing.JTextField();
        jTextFieldNumeroDNI = new javax.swing.JTextField();
        jTextFieldCorreoElectronico = new javax.swing.JTextField();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        BotonRegistrarCliente = new javax.swing.JButton();
        ApellidoMaterno = new javax.swing.JLabel();
        jTextFieldApellidoMCliente = new javax.swing.JTextField();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(128, 64, 0));
        jTextField2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 48)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("    Registro del Cliente");
        jTextField2.setAutoscrolls(false);
        jTextField2.setBorder(null);
        jTextField2.setFocusable(false);
        jTextField2.setRequestFocusEnabled(false);
        jTextField2.setVerifyInputWhenFocusTarget(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1080, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/REGISTRARCLIENTE.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 400, 400));

        ApellidoPaterno.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        ApellidoPaterno.setText("Apellido Paterno:");
        getContentPane().add(ApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, 30));

        CorreoElectronico.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        CorreoElectronico.setText("Correo Electronico:");
        getContentPane().add(CorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, -1, 30));

        NumeroDNI.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        NumeroDNI.setText("Numero de DNI:");
        getContentPane().add(NumeroDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, 30));

        nombres.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        nombres.setText("Nombres:");
        getContentPane().add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 30));

        BotonSubirImagen.setBackground(new java.awt.Color(102, 102, 102));
        BotonSubirImagen.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        BotonSubirImagen.setForeground(new java.awt.Color(255, 255, 255));
        BotonSubirImagen.setText("Subir imagen...");
        BotonSubirImagen.setBorder(null);
        BotonSubirImagen.setBorderPainted(false);
        BotonSubirImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BotonSubirImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 210, 30));
        getContentPane().add(jTextFieldApellidoPCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 370, 40));
        getContentPane().add(jTextFieldNumeroDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 370, 40));
        getContentPane().add(jTextFieldCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 370, 40));
        getContentPane().add(jTextFieldNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 370, 40));

        BotonRegistrarCliente.setBackground(new java.awt.Color(128, 64, 0));
        BotonRegistrarCliente.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        BotonRegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistrarCliente.setText("REGISTRAR");
        BotonRegistrarCliente.setBorder(null);
        BotonRegistrarCliente.setBorderPainted(false);
        BotonRegistrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, 200, 60));

        ApellidoMaterno.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        ApellidoMaterno.setText("Apellido Materno:");
        getContentPane().add(ApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, 30));
        getContentPane().add(jTextFieldApellidoMCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 370, 40));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void BotonRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarClienteActionPerformed

    }//GEN-LAST:event_BotonRegistrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRegistroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoMaterno;
    private javax.swing.JLabel ApellidoPaterno;
    private javax.swing.JButton BotonRegistrarCliente;
    private javax.swing.JButton BotonSubirImagen;
    private javax.swing.JLabel CorreoElectronico;
    private javax.swing.JLabel NumeroDNI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldApellidoMCliente;
    private javax.swing.JTextField jTextFieldApellidoPCliente;
    private javax.swing.JTextField jTextFieldCorreoElectronico;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldNumeroDNI;
    private javax.swing.JLabel nombres;
    // End of variables declaration//GEN-END:variables
}
